coursepicker/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
	# url(r'^$', include('django.contrib.flatpages.urls')),
	# url(r'^$', include('courses.urls', namespace="courses")),
	# url(r'^depts/' ),
	url(r'', include('courses.urls', namespace="courses")),
    url(r'^admin/', include(admin.site.urls)),
]

courses/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^$', views.home, name='home'),
	url(r'^search/$', views.search, name='search'),
	url(r'^courses/filtered/$', views.filter_by_dept, name='filtered'),
	#ex: /courses/
	url(r'^courses/$', views.index, name='index'),
	#ex: /courses/5/
	url(r'^courses/(?P<course_id>[0-9]+)/$', views.course_detail, name='course_detail'),

	# url(r'^depts/(?P<dept_id>[0-9]+)/$', views.dept_detail, name='dept_detail'),
	]

courses/models.py
from django.db import models

class Course(models.Model):
	name = models.CharField(max_length=100)
	period = models.ForeignKey('Period', blank=True, null=True)
	professors = models.ManyToManyField('Prof', blank=True)
	term = models.ForeignKey('Term', blank=True, null=True)
	dept = models.ForeignKey('Dept', null=True, blank=True)
	number = models.CharField(max_length=100, blank=True, null=True)
	section = models.CharField(max_length=100, blank=True, null=True)
	CRN = models.CharField(max_length=10, blank=True, unique=True)
	limit = models.CharField(max_length=100, default="-")
	enrollment = models.CharField(max_length=100, default="-")
	building = models.CharField(max_length=100, blank=True, null=True)
	room = models.CharField(max_length=100, blank=True, null=True)
	distribs = models.ManyToManyField('Distrib', blank=True)
	WC = models.ForeignKey('WC', blank=True, null=True)
	description = models.CharField(max_length=1000, blank=True)

	def __str__(self):
		return self.name

class Prof(models.Model):
	first_name = models.CharField(max_length=50)
	last_name = models.CharField(max_length=50)
	fullname = models.CharField(max_length=50, blank=True, unique=True)
	dept = models.ForeignKey('Dept', null=True, blank=True)

	def __str__(self):
		return self.fullname

class Dept(models.Model):
	name = models.CharField(max_length=100, unique=True)
	abbrv = models.CharField(max_length=10, unique=True)

	def __str__(self):
		return self.name

class Term(models.Model):
	name = models.CharField(max_length=50, unique=True)
	abbrv = models.CharField(max_length=3, unique=True)

	def __str__(self):
		return self.name

class Period(models.Model):
	name = models.CharField(max_length=20, unique=True)

	def __str__(self):
		return self.name

class Distrib(models.Model):
	name = models.CharField(max_length=50, unique=True)
	abbrv = models.CharField(max_length=10, unique=True)

	def __str__(self):
		return self.name

class WC(models.Model):
	name = models.CharField(max_length=50, unique=True)
	abbrv = models.CharField(max_length=10, unique=True)

	def __str__(self):
		return self.name

courses/forms.py
from django import forms
from .models import Dept

DEPT_CHOICES = [[dept.id, dept] for dept in Dept.objects.all()]

class DeptFilterForm(forms.Form):
	filterdepts = forms.MultipleChoiceField(label='', choices=DEPT_CHOICES, widget=forms.CheckboxSelectMultiple(), required=False)

class SearchForm(forms.Form):
	search = forms.CharField(label='', widget=forms.TextInput(attrs={'placeholder': 'Search'}))

courses/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, Http404
from django.template import RequestContext, loader
from django.views import generic
from .models import Course, Dept, Prof
from .forms import DeptFilterForm, SearchForm
# Create your views here.

def home(request):
	form = DeptFilterForm()
	return render(request, 'courses/home.html', {'form': form})

def search(request):
	if request.method == 'GET':
		form = SearchForm(request.GET)
		if form.is_valid():
			entry = form.cleaned_data['search']
			searchcourses = []
			for course in Course.objects.filter(name__contains=entry):
				searchcourses.append(course)
			for prof in Prof.objects.filter(fullname__contains=entry):
				for course in prof.course_set.all():
					searchcourses.append(course)
			return render(request, 'courses/search.html', {'entry': entry, 'searchcourses': searchcourses})


def filter_by_dept(request):
	if request.method == 'GET':
		form = DeptFilterForm(request.GET)
		if form.is_valid():
			filterdepts = form.cleaned_data['filterdepts']
			filteredcourses = []
			i=0
			while (i < len(filterdepts)):
				for course in Dept.objects.get(id=filterdepts[i]).course_set.all():
					filteredcourses.append(course)
				i += 1

			return render(request, 'courses/filtered.html', {'filteredcourses': filteredcourses})

def index(request):
	course_list = Course.objects.order_by('dept')

	template = loader.get_template('courses/index.html')
	context = RequestContext(request, {
		'course_list': course_list,
	})
	return HttpResponse(template.render(context))

def course_detail(request, course_id):
	try:
		course = Course.objects.get(pk=course_id)
	except Course.DoesNotExist:
		raise Http404("Course does not exist")

	# singleprof = Prof.objects.get(fullname=course.prof)
	return render(request, 'courses/course_detail.html', {'course': course})

courses/templates/courses/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="{% static "courses/base_style.css" %}">
    <title>{% block title %}Course Picker{% endblock %}</title>
</head>

<body>
    <div id="topbar">
        {% block topbar %}
        <h1> Dartmouth Course Picker </h1>
        <ul>
            <li><a href="{% url 'courses:home' %}">Home</a></li>
            <li><a href="/courses/">Index</a></li>
        </ul>
        <form action="{% url 'courses:search' %}" method="get" id="searchbox">
            {{ search_form }}
        </form>
        {% endblock %}
    </div>

    <div id="content">
        {% block content %}{% endblock %}
    </div>
</body>
</html>

courses/templates/courses/course_detail.html
{% extends "courses/base.html" %}
{% load staticfiles %}
<!DOCTYPE html>

<link rel="stylesheet" href="base_style.css">

<title>{% block title %} {{ course.dept.abbrv }} {{course.num}} {% endblock %}</title>

{% block content %}
<h1>{{ course.dept.abbrv }} {{ course.number }}: {{ course.name }} </h1>
<p>
	Professors:
	{% for prof in course.professors.all %}
		{{ prof.first_name }} {{ prof.last_name }}, 
	{% endfor %}
</p>
<p>Description: {{course.description}}
<p>Enrollment: {{ course.enrollment }}/{{ course.limit }}
<p>Period: {{ course.period }}</p>
<p>Location: {{ course.building }} {{ course.room }}</p>
<p>CRN: {{ course.CRN }}

{% endblock %}

courses/templates/courses/filtered.html
{% extends "courses/base.html" %}
{% load staticfiles %}

<!-- <link rel="stylesheet" type="text/css" href="{% static 'courses/style.css' %}" /> -->

{% block content %}
	<div id="filtered">
		<h1>Results</h1>

		<table id="t01">
			<tr>
				<th>Course</th>
				<th></th>
				<th>Professor</th>
				<th></th>
				<th>Period</th>
				<th></th>
				<th>Enrollment</th>
				<th></th>
				<th>WC</th>
				<th></th>
				<th>Dist(s)</th>
			</tr>
			{% for course in filteredcourses %}
			<tr>
				<td><a href="{% url 'courses:course_detail' course.id %}">{{ course.name }}</a></td>
				<td></td>
				<td>
					{% for prof in course.professors.all %}
						{{prof.first_name}} {{prof.last_name}}
					{% endfor %}
				</td>
				<td></td>
				<td>
					{{course.period}}
				</td>
				<td></td>
				<td>
					{{course.enrollment}}/{{course.limit}}
				</td>
				<td></td>
				<td>
					{{course.WC}}
				</td>
				<td></td>
				<td>
					{% for distrib in course.distribs.all %}
						{{distrib.abbrv}}
					{% endfor %}
				</td>
			</tr>
			{% endfor %}
		</table>
	</div>
{% endblock %}

courses/templates/courses/home.html
{% extends "courses/base.html" %}
{% load staticfiles %}

{% block content %}
	<div id="home">
		<h3>Pick by department</h3>

		<form action="{% url 'courses:filtered' %}" method="get" id="deptsortlist">
			{{ form }}
			<input type="submit" value="Go" />
		</form>
	</div>
{% endblock %}

courses/templates/courses/index.html
{% extends "courses/base.html" %}
{% load staticfiles %}

<!-- <link rel="stylesheet" type="text/css" href="{% static 'courses/style.css' %}" /> -->

{% block content %}

	<h1>Courses</h1>


{% if course_list %}
    <ul>
    {% for course in course_list %}
        <li><a href="{% url 'courses:course_detail' course.id %}">{{ course.dept.abbrv }} {{ course.num }}: {{ course.name }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No courses are available.</p>
{% endif %}
{% endblock %}

courses/templates/courses/search.html
{% extends "courses/base.html" %}
{% load staticfiles %}

{% block content %}
	<div id="search">
		<h2>Search Results For "{{entry}}"</h2>

		{% if searchcourses %}
		<table id="t02">
			<tr>
				<th>Course</th>
				<th></th>
				<th>Professor</th>
				<th></th>
				<th>Period</th>
				<th></th>
				<th>Enrollment</th>
			</tr>
			{% for course in searchcourses %}
			<tr>
				<td><a href="{% url 'courses:course_detail' course.id %}">{{ course.name }}</a></td>
				<td></td>
				<td>
					{% for prof in course.professors.all %}
						{{prof.first_name}} {{prof.last_name}}
					{% endfor %}
				</td>
				<td></td>
				<td>
					{{course.period}}
				</td>
				<td></td>
				<td>
					{{course.enrollment}}/{{course.limit}}
				</td>
			</tr>
			{% endfor %}
		</table>

		{% else %}
		<p>No results found :(<p>
		{% endif %}
	</div>
{% endblock %}